/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ClassificationSchema extends BaseModel {
  static $columns = [
    'archivedAt',
    'createdAt',
    'description',
    'id',
    'ministryId',
    'name',
    'updatedAt',
  ] as const
  $columns = ClassificationSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ministryId: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FolderSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ministryId', 'name', 'updatedAt'] as const
  $columns = FolderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ministryId: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InviteSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'createdByUserId',
    'expiresAt',
    'id',
    'ministryId',
    'revokedAt',
  ] as const
  $columns = InviteSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ministryId: string
  @column.dateTime()
  declare revokedAt: DateTime | null
}

export class MemberFunctionSchema extends BaseModel {
  static $columns = ['functionId', 'membershipId'] as const
  $columns = MemberFunctionSchema.$columns
  @column()
  declare functionId: string
  @column({ isPrimary: true })
  declare membershipId: string
}

export class MembershipSchema extends BaseModel {
  static $columns = [
    'canEditScheduleSongs',
    'canManageFunctions',
    'canManageRepertoire',
    'canManageSchedules',
    'createdAt',
    'id',
    'isAdmin',
    'ministryId',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = MembershipSchema.$columns
  @column()
  declare canEditScheduleSongs: boolean
  @column()
  declare canManageFunctions: boolean
  @column()
  declare canManageRepertoire: boolean
  @column()
  declare canManageSchedules: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isAdmin: boolean
  @column()
  declare ministryId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class MinistrySchema extends BaseModel {
  static $columns = [
    'color',
    'createdAt',
    'id',
    'musicModuleEnabled',
    'name',
    'timezone',
    'updatedAt',
  ] as const
  $columns = MinistrySchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare musicModuleEnabled: boolean
  @column()
  declare name: string
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MinistryFunctionSchema extends BaseModel {
  static $columns = [
    'archivedAt',
    'createdAt',
    'id',
    'ministryId',
    'name',
    'sortOrder',
    'updatedAt',
  ] as const
  $columns = MinistryFunctionSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ministryId: string
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetSchema extends BaseModel {
  static $columns = ['codeHash', 'createdAt', 'expiresAt', 'id', 'usedAt', 'userId'] as const
  $columns = PasswordResetSchema.$columns
  @column({ serializeAs: null })
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: string
}

export class SongLinkSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'kind',
    'label',
    'songId',
    'updatedAt',
    'url',
    'versionId',
  ] as const
  $columns = SongLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare label: string
  @column()
  declare songId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare versionId: string | null
}

export class SongVersionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'name', 'songId', 'updatedAt'] as const
  $columns = SongVersionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string | null
  @column()
  declare name: string
  @column()
  declare songId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SongSchema extends BaseModel {
  static $columns = [
    'artist',
    'bpm',
    'classificationId',
    'createdAt',
    'defaultKey',
    'deletedAt',
    'durationSeconds',
    'folderId',
    'id',
    'ministryId',
    'title',
    'updatedAt',
  ] as const
  $columns = SongSchema.$columns
  @column()
  declare artist: string | null
  @column()
  declare bpm: number | null
  @column()
  declare classificationId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultKey: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare durationSeconds: number | null
  @column()
  declare folderId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ministryId: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'authVersion',
    'birthDate',
    'createdAt',
    'email',
    'id',
    'name',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare authVersion: number
  @column.date()
  declare birthDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
