/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Account: () => import('#controllers/account_controller'),
  Calendars: () => import('#controllers/calendars_controller'),
  Chats: () => import('#controllers/chats_controller'),
  Classifications: () => import('#controllers/classifications_controller'),
  Folders: () => import('#controllers/folders_controller'),
  Generations: () => import('#controllers/generations_controller'),
  Health: () => import('#controllers/health_controller'),
  Integrations: () => import('#controllers/integrations_controller'),
  Invites: () => import('#controllers/invites_controller'),
  Members: () => import('#controllers/members_controller'),
  Ministries: () => import('#controllers/ministries_controller'),
  MinistryFunctions: () => import('#controllers/ministry_functions_controller'),
  Notices: () => import('#controllers/notices_controller'),
  Notifications: () => import('#controllers/notifications_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Reports: () => import('#controllers/reports_controller'),
  Schedules: () => import('#controllers/schedules_controller'),
  Scripts: () => import('#controllers/scripts_controller'),
  Session: () => import('#controllers/session_controller'),
  Shares: () => import('#controllers/shares_controller'),
  Songs: () => import('#controllers/songs_controller'),
  Spreadsheets: () => import('#controllers/spreadsheets_controller'),
  Unavailabilities: () => import('#controllers/unavailabilities_controller'),
}
